describe('Test the discography page', () => {
	it('visits the discography url', () => {
		cy.visit('/discography')

		cy.title().should('eq', 'U P P E R C A S E')
		cy.get('[data-testid="discography"]').should('exist')
		cy.get('[data-testid="discography"]').should('have.length', 1)
		cy.get('[data-testid="discography-header"]').should('exist')
		cy.get('[data-testid="discography-header"]').should('have.length', 1)
		cy.get('[data-testid="discography-headline"]').should('exist')
		cy.get('[data-testid="discography-headline"]').should('have.length', 1)
        cy.get('[data-testid="release-item"]').should('exist')
		cy.get('[data-testid="release-item"]').should('have.length', 6)
        cy.get('[data-testid="release-thumbnail"]').should('exist')
        cy.get('[data-testid="release-thumbnail"]').should('have.length', 6)
        cy.get('[data-testid="release-title"]').should('exist')
        cy.get('[data-testid="release-title"]').should('have.length', 6)
        cy.get('[data-testid="release-date"]').should('exist')
        cy.get('[data-testid="release-date"]').should('have.length', 6)
        cy.get('[data-testid="release-url"]').should('exist')
        cy.get('[data-testid="release-url"]').should('have.length', 6)
	})

	it('clicks the discography link', () => {
		cy.visit('/')
        cy.get('[data-testid="discography-link"]').should('exist')
		cy.get('[data-testid="discography-link"]').should('have.length', 1)
		cy.get('[data-testid="discography-link"]').click()

		cy.url().should('include', '/discography')

		cy.title().should('eq', 'U P P E R C A S E')
		cy.get('[data-testid="discography"]').should('exist')
		cy.get('[data-testid="discography"]').should('have.length', 1)
		cy.get('[data-testid="discography-header"]').should('exist')
		cy.get('[data-testid="discography-header"]').should('have.length', 1)
		cy.get('[data-testid="discography-headline"]').should('exist')
		cy.get('[data-testid="discography-headline"]').should('have.length', 1)
        cy.get('[data-testid="release-item"]').should('exist')
		cy.get('[data-testid="release-item"]').should('have.length', 6)
        cy.get('[data-testid="release-thumbnail"]').should('exist')
        cy.get('[data-testid="release-thumbnail"]').should('have.length', 6)
        cy.get('[data-testid="release-title"]').should('exist')
        cy.get('[data-testid="release-title"]').should('have.length', 6)
        cy.get('[data-testid="release-date"]').should('exist')
        cy.get('[data-testid="release-date"]').should('have.length', 6)
        cy.get('[data-testid="release-url"]').should('exist')
        cy.get('[data-testid="release-url"]').should('have.length', 6)
	})
})
