describe('Test the events page', () => {
	it('visits the events url', () => {
		cy.visit('/events')

		cy.title().should('eq', 'U P P E R C A S E')
		cy.get('[data-testid="events"]').should('exist')
		cy.get('[data-testid="events"]').should('have.length', 1)
		cy.get('[data-testid="events-header"]').should('exist')
		cy.get('[data-testid="events-header"]').should('have.length', 1)
        cy.get('[data-testid="event-item"]').should('exist')
		cy.get('[data-testid="event-item"]').should('have.length', 6)
		cy.get('[data-testid="event-title"]').should('exist')
		cy.get('[data-testid="event-title"]').should('have.length', 6)
		cy.get('[data-testid="event-date"]').should('exist')
		cy.get('[data-testid="event-date"]').should('have.length', 6)
		cy.get('[data-testid="event-location"]').should('exist')
		cy.get('[data-testid="event-location"]').should('have.length', 6)
		cy.get('[data-testid="event-content"]').should('exist')
		cy.get('[data-testid="event-content"]').should('have.length', 6)
		cy.get('[data-testid="event-url"]').should('exist')
		cy.get('[data-testid="event-url"]').should('have.length', 6)
	})

	it('clicks the events link', () => {
		cy.visit('/')
        cy.get('[data-testid="events-link"]').should('exist')
		cy.get('[data-testid="events-link"]').should('have.length', 1)
		cy.get('[data-testid="events-link"]').click()

		cy.url().should('include', '/events')

		cy.title().should('eq', 'U P P E R C A S E')
		cy.get('[data-testid="events"]').should('exist')
		cy.get('[data-testid="events"]').should('have.length', 1)
		cy.get('[data-testid="events-header"]').should('exist')
		cy.get('[data-testid="events-header"]').should('have.length', 1)
        cy.get('[data-testid="event-item"]').should('exist')
		cy.get('[data-testid="event-item"]').should('have.length', 6)
		cy.get('[data-testid="event-title"]').should('exist')
		cy.get('[data-testid="event-title"]').should('have.length', 6)
		cy.get('[data-testid="event-date"]').should('exist')
		cy.get('[data-testid="event-date"]').should('have.length', 6)
		cy.get('[data-testid="event-location"]').should('exist')
		cy.get('[data-testid="event-location"]').should('have.length', 6)
		cy.get('[data-testid="event-content"]').should('exist')
		cy.get('[data-testid="event-content"]').should('have.length', 6)
		cy.get('[data-testid="event-url"]').should('exist')
		cy.get('[data-testid="event-url"]').should('have.length', 6)
	})
})
